# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-08 05:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashmessage',
            name='body',
            field=models.CharField(default='default text', max_length=160),
            preserve_default=False,
        ),
    ]
