# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-08 06:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_flashmessage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashmessage',
            name='location',
            field=models.CharField(default='Nepal', max_length=100),
            preserve_default=False,
        ),
    ]
