# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-15 20:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_auto_20170703_1349'),
        ('cms', '0003_flashmessage_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashmessage',
            name='report',
            field=models.ForeignKey(default='List', on_delete=django.db.models.deletion.CASCADE, to='reports.Report'),
            preserve_default=False,
        ),
    ]
