# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 21:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_auto_20170628_2141'),
        ('accounts', '0003_profile_sub_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='sub_country',
        ),
        migrations.AddField(
            model_name='profile',
            name='sub_country',
            field=models.ManyToManyField(to='reports.Country'),
        ),
    ]
