# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20170630_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_moderator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_publisher',
            field=models.BooleanField(default=False),
        ),
    ]
