# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-22 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20170716_0133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_moderator',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_publisher',
            field=models.NullBooleanField(default=False),
        ),
    ]
