# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-12 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20170723_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='trial_sub',
            field=models.NullBooleanField(default=False),
        ),
    ]
