# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 20:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rating', models.CharField(choices=[('L', 'Low'), ('M', 'Medium'), ('H', 'High'), ('Ex', 'Extreme')], max_length=2)),
                ('risk_bg', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=500)),
                ('summary', models.TextField()),
                ('assessment', models.TextField()),
                ('impact_tc', models.CharField(max_length=500)),
                ('advice', models.TextField()),
                ('event_bg_title', models.CharField(max_length=300)),
                ('event_bg_text', models.TextField()),
                ('latitude', models.DecimalField(decimal_places=4, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=4, max_digits=10)),
                ('impact_radius', models.IntegerField()),
                ('report_type', models.CharField(max_length=25)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.Country')),
            ],
        ),
    ]
