# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('T', 'Travel'), ('C', 'Country'), ('TC', 'Travel & Country')], default='T', max_length=3),
        ),
    ]
