# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 06:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_auto_20170701_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='flag',
            field=models.ImageField(null=True, upload_to='flags'),
        ),
    ]
