# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 06:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_auto_20170701_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='country',
            name='flag',
            field=models.FileField(null=True, upload_to='flags'),
        ),
    ]
