# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 05:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_auto_20170701_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('T', 'Travel'), ('C', 'Country')], default='T', max_length=3),
        ),
    ]
