# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_auto_20170702_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='advice',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='assessment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='event_bg_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='event_bg_title',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='report',
            name='impact_tc',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
