# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-18 05:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_auto_20170703_1349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='archived',
            new_name='archive',
        ),
    ]
