# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-04 06:30
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0011_auto_20170718_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='advice',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='report',
            name='assessment',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='report',
            name='event_bg_text',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='report',
            name='summary',
            field=tinymce.models.HTMLField(),
        ),
    ]
