# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-04 07:37
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0012_auto_20170904_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='risk_bg',
            field=tinymce.models.HTMLField(),
        ),
    ]
