# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-25 06:38
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0013_auto_20170904_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='advice',
            field=tinymce.models.HTMLField(blank=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='assessment',
            field=tinymce.models.HTMLField(blank=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='event_bg_text',
            field=tinymce.models.HTMLField(blank=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='impact_radius',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name='report',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name='report',
            name='summary',
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
