# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-25 06:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0014_auto_20170925_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='impact_radius',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
    ]
